package com.juancho.escuela.vistas;

import com.juancho.escuela.dao.AlumnoDAO;
import com.juancho.escuela.dao.DAOException;
import com.juancho.escuela.dao.impl.FactoryDAO;

import java.util.logging.Level;
import java.util.logging.Logger;

public class ListaAlumnosView extends javax.swing.JFrame {
    private AlumnoDAO manager;
    private AlumnosTableModel model;

    public ListaAlumnosView(AlumnoDAO manager) throws DAOException {
        initComponents();
        this.manager = manager;
        this.model = new AlumnosTableModel(manager);
        this.model.updateModel();
        this.tablaAlumnos.setModel(this.model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(jButton1);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAlumnos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        AlumnoDAO manager = (AlumnoDAO) FactoryDAO.getInstance().obtenerDAO("AlumnoDAO");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListaAlumnosView(manager).setVisible(true);
                } catch (DAOException e) {
                    e.printStackTrace();
                    Logger.getLogger(ListaAlumnosView.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
